version: '3.8'

services:

  db:
    build:
      context: .
      dockerfile: docker/db.dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - app-data:/app/data

volumes:
  app-data:

