version: "3.8"
networks:
  app_network:
    driver: host
services:
  db:
    build:
      context: .
      dockerfile: docker/db.dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  app_test:
    build:
      context: .
      dockerfile: docker/test.dockerfile
    depends_on:
      - db
      - app
    env_file: .env
    volumes:
      - .:/app
    environment:
      POSTGRES_URL: postgresql://postgres:1234@db:5432/postgres
